
# STU-DOSBox

# /home/jbalcomb/STU/devel/STU-Extras/STU-DOSBox/stu-dosbox.conf



[sdl]
fullscreen = false
output     = surface

[dosbox]
machine  = svga_s3
memsize  = 16

[cpu]
# Pin core=normal so CPU_Core_Normal_Run
core = normal

[autoexec]
@echo off
mount c /home/jbalcomb/STU_DBWD/MoM131
c:
MAGIC.EXE
# WIZARDS.EXE
